### ISSUE TITLE
Error when try to change the IP address

### ISSUE THREAD

**Issue by faiz4h61** [benhowell/examples#3]
ConnectionError: HTTPConnectionPool(host='192.168.0.100', port=80): Max retries exceeded with url: /?action=stream (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae126a84d0>: Failed to establish a new connection: [Errno 113] No route to host',))

**Comment by benhowell** [comment]
This isn't an error with this example. It looks like you have problems elsewhere (e.g. you've got the address wrong, the port wrong, the port is closed). It could be any number of things
